services:
  postgres:
    image: postgres:16
    container_name: cronos_postgres
    restart: always
    environment:
      POSTGRES_DB: cronos_db
      POSTGRES_USER: cronos_user
      POSTGRES_PASSWORD: cronos_password
    ports:
      - "5432:5432"
    volumes:
      - cronos_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: cronos_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: cronos_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  cronos_postgres_data: